project:
  type: website
  output-dir: docs

website:
  title: "Yousuf Ali"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Yousuf28
format:
  html:
    theme: solar
    css: styles.css



